### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by aantn** [vega/vue-vega#4]
Hi all,
I'm interested in using this. Are there any major tasks that remain to be done before this is production ready? I would be happy to contribute and finish up anything that remains.

**Comment by domoritz** [comment]
Yes, see #1

**Comment by aantn** [comment]
@domoritz #1 primarily covers the dev environment. Is there anything that has to be done other than the tooling? For example, would you like to expose Vega as a standard Vue component `<vega :data :spec :etc>` that can be used in templates? Or is the plan only to expose composition API useMethods?

Something like `<vega>` seems more natural to me because you can embed it in templates, but I admittedly don't have much experience with the compositions API.

**Comment by domoritz** [comment]
Templates sound reasonable to me but I don't have much experience with vue. 

@nesterone and @jsbroks what's your plan?
